const dataPerWeek = [
  {'day': 'Lunes', 'value': 1000, 'group': 'Actual'},
  {'day': 'Martes', 'value': 2000, 'group': 'Actual'},
  {'day': 'Miercoles', 'value': 3500, 'group': 'Actual'},
  {'day': 'Jueves', 'value': 6000, 'group': 'Actual'},
  {'day': 'Viernes', 'value': 7500, 'group': 'Actual'},
  {'day': 'Sabado', 'value': 9500, 'group': 'Actual'},
  {'day': 'Domingo', 'value': 10000, 'group': 'Actual'},
  {'day': 'Lunes', 'value': 5500, 'group': 'Anterior'},
  {'day': 'Martes', 'value': 500, 'group': 'Anterior'},
  {'day': 'Miercoles', 'value': 2500, 'group': 'Anterior'},
  {'day': 'Jueves', 'value': 5500, 'group': 'Anterior'},
  {'day': 'Viernes', 'value': 4000, 'group': 'Anterior'},
  {'day': 'Sabado', 'value': 1000, 'group': 'Anterior'},
  {'day': 'Domingo', 'value': 3000, 'group': 'Anterior'},
];
const dataPerMonth = [
  {'day': 'S1', 'value': 10, 'group': 'Mes actual'},
  {'day': 'S2', 'value': 20, 'group': 'Mes actual'},
  {'day': 'S3', 'value': 35, 'group': 'Mes actual'},
  {'day': 'S4', 'value': 60, 'group': 'Mes actual'},
  {'day': 'S1', 'value': 55, 'group': 'Mes anterior'},
  {'day': 'S2', 'value': 5, 'group': 'Mes anterior'},
  {'day': 'S3', 'value': 25, 'group': 'Mes anterior'},
  {'day': 'S4', 'value': 55, 'group': 'Mes anterior'},
];
const dataPerYear = [
  {'day': 'Enero', 'value': 10, 'group': 'Año actual'},
  {'day': 'Febrero', 'value': 20, 'group': 'Año actual'},
  {'day': 'Marzo', 'value': 35, 'group': 'Año actual'},
  {'day': 'Abril', 'value': 15, 'group': 'Año actual'},
  {'day': 'Mayo', 'value': 25, 'group': 'Año actual'},
  {'day': 'Junio', 'value': 28, 'group': 'Año actual'},
  {'day': 'Julio', 'value': 8, 'group': 'Año actual'},
  {'day': 'Agosto', 'value': 7, 'group': 'Año actual'},
  {'day': 'Septiembre', 'value': 16, 'group': 'Año actual'},
  {'day': 'Octubre', 'value': 24, 'group': 'Año actual'},
  {'day': 'Noviembre', 'value': 40, 'group': 'Año actual'},
  {'day': 'Diciembre', 'value': 42, 'group': 'Año actual'},
  //? otro anio
  {'day': 'Enero', 'value': 28, 'group': 'Año anterior'},
  {'day': 'Febrero', 'value': 11, 'group': 'Año anterior'},
  {'day': 'Marzo', 'value': 35, 'group': 'Año anterior'},
  {'day': 'Abril', 'value': 66, 'group': 'Año anterior'},
  {'day': 'Mayo', 'value': 0, 'group': 'Año anterior'},
  {'day': 'Junio', 'value': 60, 'group': 'Año anterior'},
  {'day': 'Julio', 'value': 71, 'group': 'Año anterior'},
  {'day': 'Agosto', 'value': 45, 'group': 'Año anterior'},
  {'day': 'Septiembre', 'value': 60, 'group': 'Año anterior'},
  {'day': 'Octubre', 'value': 39, 'group': 'Año anterior'},
  {'day': 'Noviembre', 'value': 22, 'group': 'Año anterior'},
  {'day': 'Diciembre', 'value': 10, 'group': 'Año anterior'},
];
